# Section a

In [1]:
from nms import nms_with_class_hierarchy
from lca import BinaryLCA

lca = BinaryLCA("asset/hierarchy.txt")

In [2]:
lca.find_all_ancestor("n02424589")

['n02424305',
 'n02419796',
 'n02401031',
 'n02399000',
 'n02394477',
 'n02370806',
 'n01886756',
 'n01861778',
 'n01471682',
 'n01466257',
 'n00015388',
 'n00004475',
 'n00004258',
 'n00003553',
 'n00002684',
 'n00001930',
 'n00001740']

# Section c

In [3]:
import numpy as np

# Define the size of the array
num_rows = 10

# Define the range for xmin, ymin, xmax, ymax
min_coord = 0
max_coord = 50

# Define the range for the score
min_score = 0.6
max_score = 1.0

# Define the class names
# Here n02119477 and n02119789 are children of n02118333
class_names = ["n02118333", "n02119477", "n02119789"]

# Generate the random array
random_array = np.zeros((num_rows, 5), dtype=np.float32)
random_classes = []

for i in range(num_rows):
    # Generate random values for xmin, ymin, xmax, ymax
    xmin = np.random.randint(min_coord, max_coord)
    ymin = np.random.randint(min_coord, max_coord)
    xmax = np.random.randint(xmin+1, max_coord)
    ymax = np.random.randint(ymin+1, max_coord)
    
    # Generate a random score
    score = np.random.uniform(min_score, max_score)
    
    # Select a random class name
    class_name = np.random.choice(class_names)
    
    # Assign the values to the array
    random_array[i] = [xmin, ymin, xmax, ymax, score]
    random_classes.append(class_name)

print(random_array)
print(random_classes)


[[22.         22.         29.         47.          0.7724032 ]
 [ 0.         10.         22.         47.          0.8225007 ]
 [32.         31.         33.         32.          0.98753715]
 [ 6.         28.          8.         37.          0.60695344]
 [18.          6.         21.         20.          0.96375704]
 [31.          5.         41.         12.          0.9780806 ]
 [42.         26.         45.         30.          0.80951756]
 [10.         19.         16.         40.          0.7333392 ]
 [29.         37.         44.         42.          0.91993076]
 [45.         22.         49.         38.          0.6187    ]]
['n02119477', 'n02119477', 'n02119477', 'n02118333', 'n02119789', 'n02118333', 'n02119789', 'n02119477', 'n02119789', 'n02119789']


In [4]:
bounding_boxes = random_array[:,:4]
confidence_scores = random_array[:,4]
class_labels = random_classes
selected_boxes, selected_scores, selected_classes = nms_with_class_hierarchy(bounding_boxes, confidence_scores,\
                                                                             class_labels, lca,\
                                                                             0.6, 0.5)
print('Selected boxes:', selected_boxes)
print('Selected scores:', selected_scores)
print('Selected classes:', selected_classes)

print(len(selected_boxes))

Selected boxes: [array([32., 31., 33., 32.], dtype=float32), array([31.,  5., 41., 12.], dtype=float32), array([18.,  6., 21., 20.], dtype=float32), array([29., 37., 44., 42.], dtype=float32), array([ 0., 10., 22., 47.], dtype=float32), array([42., 26., 45., 30.], dtype=float32), array([22., 22., 29., 47.], dtype=float32), array([10., 19., 16., 40.], dtype=float32), array([45., 22., 49., 38.], dtype=float32), array([ 6., 28.,  8., 37.], dtype=float32)]
Selected scores: [0.98753715, 0.9780806, 0.96375704, 0.91993076, 0.8225007, 0.80951756, 0.7724032, 0.7333392, 0.6187, 0.60695344]
Selected classes: ['n02119477', 'n02118333', 'n02119789', 'n02119789', 'n02119477', 'n02119789', 'n02119477', 'n02119477', 'n02119789', 'n02118333']
10
